services:
  # server:
  #   container_name: snippet-flow-server
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DATABASE_URL=postgresql://username:password@db:5432/snippet-flow-db
  #   depends_on:
  #     - db
  db:
    image: ankane/pgvector # postgres with pgvector extension
    container_name: snippet-flow-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippet-flow-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
